apiVersion: v1
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: slack-notification
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        send_resolved: true
        channel: '#alert'
    route:
      group_interval: 5m
      group_wait: 10s
      receiver: slack-notification
      repeat_interval: 3h
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-09-16T13:34:06Z"
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-11.12.1
    component: alertmanager
    heritage: Helm
    release: prometheus
  name: prometheus-alertmanager
  namespace: default
  resourceVersion: "776901"
